### ISSUE TITLE
Exception when deleting stream

### ISSUE THREAD

**Issue by mcpride** [jjrdk/NEventStore.Contrib#1]
FirebirdSqlPersistenceEngine.DeleteStream(...) throws following exception:

FirebirdSql.Data.FirebirdClient.FbException was unhandled by user code
  HResult=-2147467259
  Message=Dynamic SQL Error
SQL error code = -104
Token unknown - line 2, column 1
DELETE
  Source=FirebirdSql.Data.FirebirdClient
  ErrorCode=335544569
  SQLSTATE=42000
  StackTrace:
       bei FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteNonQuery() in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\FirebirdClient\FbCommand.cs:Zeile 503.
       bei NEventStore.Contrib.Persistence.SqlDialects.CommonDbStatement.ExecuteNonQuery(String commandText)
  InnerException: FirebirdSql.Data.Common.IscException
       HResult=-2146233088
       Message=Dynamic SQL Error
SQL error code = -104
Token unknown - line 2, column 1
DELETE
       Source=FirebirdSql.Data.FirebirdClient
       ErrorCode=335544569
       IsWarning=false
       SQLSTATE=42000
       StackTrace:
            bei FirebirdSql.Data.Client.Native.FesDatabase.ProcessStatusVector(IntPtr[] statusVector) in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\Client\Native\FesDatabase.cs:Zeile 368.
            bei FirebirdSql.Data.Client.Native.FesStatement.Prepare(String commandText) in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\Client\Native\FesStatement.cs:Zeile 302.
            bei FirebirdSql.Data.FirebirdClient.FbCommand.Prepare(Boolean returnsSet) in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\FirebirdClient\FbCommand.cs:Zeile 1180.
            bei FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteCommand(CommandBehavior behavior, Boolean returnsSet) in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\FirebirdClient\FbCommand.cs:Zeile 1192.
            bei FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteCommand(CommandBehavior behavior) in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\FirebirdClient\FbCommand.cs:Zeile 1185.
            bei FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteNonQuery() in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\FirebirdClient\FbCommand.cs:Zeile 482.
       InnerException:

**Comment by jjrdk** [comment]
Thank you for reporting the problem.  Can you please provide a failing test case?

**Comment by mcpride** [comment]
Yes, please add this to your persistence tests:

```
public class when_deleting_a_stream : PersistenceEngineConcern
    {
        private ICommit _commit;

        protected override void Context()
        {
            _commit = Persistence.CommitSingle(Guid.NewGuid().ToString());
            Persistence.AddSnapshot(new Snapshot(_commit.BucketId, _commit.StreamId, _commit.StreamRevision, "SnapshotData"));
        }

        protected override void Because()
        {
            Persistence.DeleteStream(_commit.BucketId, _commit.StreamId);
        }

        [Fact]
        public void should_not_find_stream()
        {
            Persistence.GetFrom(_commit.BucketId, _commit.StreamId, 0, int.MaxValue).Count().ShouldBe(0);
        }

        [Fact]
        public void should_not_find_any_snapshots_to_stream()
        {
            Persistence.GetSnapshot(_commit.BucketId, _commit.StreamId, _commit.StreamRevision).ShouldBeNull();
        }
    }
```

**Comment by mcpride** [comment]
Would be fine if you also update the nuget Package!

**Comment by jjimenezroda** [comment]
Hi @mcpride,

package is now available! Thanks for the contribution!

Regards!
